kind: pipeline
type: docker
name: default

steps:
  - name: Tubearchivist
    image: stiforr/ci-tools:1
    commands:
      - helm package charts/tube-archivist
      - helm repo index --url https://insuusvenerati.github.io/helm-charts/ .