apiVersion: v2
appVersion: v0.1.5
dependencies:
  - name: rejson
    repository: file://charts/rejson
    version: 0.1.0
  - name: elasticsearch
    repository: https://Helm.elastic.co
    version: 7.17.1
description: A Helm chart for Kubernetes
name: tubearchivist
type: application
version: 0.4.4
