# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: bbilly1/tubearchivist
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

elasticsearch:
  persistence:
    enabled: true
  volumeClaimTemplate:
    resources:
      requests:
        storage: 5Gi
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  replicas: 1
  # -- Elasticsearch environment variables
  extraEnvs:
    - name: ES_JAVA_OPTS
      value: "-Xms512m -Xmx512m"
      # -- Required. Needs to be the same as ELASTIC_PASSWORD below
    - name: ELASTIC_PASSWORD
      value: ""

login:
  username: admin
  password: changeme
  
timezone: America/Chicago

persistence:
  enabled: true
  # -- Use your storageClassName. e.g. local-path for k3s
  storageClassName: "local-path"
  size: 5Gi
  volumeMounts:
    - mountPath: "/youtube"
      name: youtube
    - mountPath: "/cache"
      name: cache

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
# fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations:
  #    cert-manager.io/cluster-issuer: letsencrypt-prod
  #    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart.domain
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
#    - secretName: tube-cert
#      hosts:
#        - chart.domain

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
