global:
  # -- Set an override for the prefix of the fullname
  nameOverride:
  # -- Set the entire name definition
  fullnameOverride:
  # -- Set additional global labels. Helm templates can be used.
  labels: {}
  # -- Set additional global annotations. Helm templates can be used.
  annotations: {}

image:
  repository: redis/redis-stack-server
  pullPolicy: IfNotPresent
  tag: "6.2.6-v3"

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true

env:
  TZ: UTC
  REDIS_ARGS: #extra arguments for Redis
  REDISEARCH_ARGS: #arguments for RediSearch
  REDISJSON_ARGS: #arguments for RedisJSON
  REDISGRAPH_ARGS: #arguments for RedisGraph
  REDISTIMESERIES_ARGS: #arguments for RedisTimeSeries
  REDISBLOOM_ARGS: #arguments for RedisBloom

service:
  main:
    enabled: true
    primary: true
    ports:
      http:
        enabled: true
        primary: true
        port: 6379
        targetPort: 6379

persistence:
  config:
    enabled: true
    mountPath: /data
    storageClass: standard
    existingClaim: 
    size: 1Gi