{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
{{ with .Values.persistence.spec }}
  {{- toYaml . | indent 2 }}
{{- end -}}
{{- end -}}